# Generated by Django 4.1.5 on 2023-03-03 22:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(30)])),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, validators=[django.core.validators.MaxLengthValidator(30)])),
                ('last_feed_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zoo.species')),
            ],
        ),
    ]
